### ISSUE TITLE
sched_getaffinity is not supported

### ISSUE THREAD

**Issue by mlvl36667** [ppopth/ethereum-shadow#1]
00:00:00.004559 [162597:shadow-worker] 00:00:00.000000000 [ERROR] [bootnode:100.0.0.1] [syscall_handler.c:543] [syscallhandler_make_syscall] Returning error ENOSYS for explicitly unsupported syscall 204 sched_getaffinity

**Comment by mlvl36667** [comment]
> That ERROR is not a problem since sched_getaffinity is not a critical system call.

Yes, but lighthouse seems to be triggering this call and my nodes fails to start with the above error message is the logs. Any ideas on how to resolve this?

**Comment by ppopth** [comment]
What lighthouse version do you use?

**Comment by mlvl36667** [comment]
> What lighthouse version do you use?

I am following the instructions in your readme, so I am using this for lighthouse: git checkout v3.4.0

**Comment by ppopth** [comment]
I just run it with a new instance of Digital Ocean droplet of 2 CPUs and 8GB of RAM and it was fine.

How do you know that your nodes failed to start?

Did your terminal show that the shadow was run successfully as follows?
```
Shadow config: the lighthouse validator client process of the node #3 is now configured in ./data/shadow.yaml
Shadow config: the lighthouse validator client process of the node #4 is now configured in ./data/shadow.yaml
** Starting Shadow e996a18f 2023-02-21--14:59:48 with GLib v2.72.4
** Shadow completed successfully
root@eth-shadow:~/ethereum-shadow# 
```

Can I also see your node's log messages? please run `cat data/shadow/hosts/node1/node1.lighthouse.1002.stderr`

Mine looks like the following
```
root@eth-shadow:~/ethereum-shadow# cat data/shadow/hosts/node1/node1.lighthouse.1002.stderr | tail -n 10
Jan 01 00:29:18.000 INFO Synced                                  slot: 132, block: 0xabef…a9ef, epoch: 4, finalized_epoch: 2, finalized_root: 0x111d…6784, exec_hash: 0xf68d…ab2c (verified), peers: 3, service: slot_notifier
Jan 01 00:29:24.001 INFO Successfully finalized deposit tree     finalized deposit count: 80, service: deposit_contract_rpc
Jan 01 00:29:24.101 INFO New block received                      root: 0x215a401698ae327f5a32ed6d19d4594f456b9645a6eb9478c5f1d541896436d2, slot: 133
Jan 01 00:29:30.000 INFO Synced                                  slot: 133, block: 0x215a…36d2, epoch: 4, finalized_epoch: 2, finalized_root: 0x111d…6784, exec_hash: 0x5d05…3f45 (verified), peers: 3, service: slot_notifier
Jan 01 00:29:36.000 INFO Prepared beacon proposer                parent_root: 0x215a401698ae327f5a32ed6d19d4594f456b9645a6eb9478c5f1d541896436d2, validator: 6, prepare_slot: 135, service: beacon
Jan 01 00:29:36.100 INFO New block received                      root: 0x1187c168155b87ae1684feddee7fbced710785f62f91d574914864f45deac362, slot: 134
Jan 01 00:29:36.100 INFO Prepared beacon proposer                parent_root: 0x1187c168155b87ae1684feddee7fbced710785f62f91d574914864f45deac362, validator: 6, prepare_slot: 135, service: beacon
Jan 01 00:29:42.000 INFO Synced                                  slot: 134, block: 0x1187…c362, epoch: 4, finalized_epoch: 2, finalized_root: 0x111d…6784, exec_hash: 0xd43b…b31f (verified), peers: 3, service: slot_notifier
Jan 01 00:29:48.000 INFO Valid block from HTTP API               slot: 135, proposer_index: 6, root: 0x8b82…6f50, block_delay: 947.275µs
Jan 01 00:29:54.001 INFO Synced                                  slot: 135, block: 0x8b82…6f50, epoch: 4, finalized_epoch: 2, finalized_root: 0x111d…6784, exec_hash: 0x7ae5…765f (verified), peers: 3, service: slot_notifier
```

**Comment by mlvl36667** [comment]
[shadow.log](https://github.com/ppopth/ethereum-shadow/files/11568788/shadow.log)

I uploaded my shadow.log file for you. cat data/shadow/hosts/node1/*.exitcode returns 111. 

The error log of lighthouse on node1 shows this: 

Unable to open testnet dir at "/home/e/shadow/ethereum-shadow/data/consensus": Unable to open deploy_block.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by ppopth** [comment]
Can I know your nodejs and npm version? Mine is
```
$ npm --version
9.5.0
$ node --version
v19.7.0
```

Can you also help me run `cat data/shadow/hosts/signernode/signernode.node.1001.*`?

If you don't mind, it will be very helpful if I can see your whole `data` directory.

Sorry for the late reply, I just got back from afk.

**Comment by mlvl36667** [comment]
My nodejs was broken. This helped:

https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver

And I had to install this:
`curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -`

Thanks for helping, I guess you can close this issue.

**Comment by ppopth** [comment]
> Thanks for helping, I guess you can close this issue.

You're welcome
